### Numpy Exercises

In [1]:
import numpy as np

In [2]:
arr2d = np.arange(1, 7).reshape(2, 3)

In [4]:
# an arithmetic operation
arr2d * arr2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
# basic indexing and slicing
print(arr2d[1, 2])
print(arr2d[1])
print(arr2d[:, 1])
print(arr2d[:1, 1:])

6
[4 5 6]
[2 5]
[[2 3]]


In [7]:
# array slices are views
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
# Boolean indexing
arr2d = np.arange(12).reshape((3, 4))
names = np.array(['Bob', 'Joe', 'Tom'])
arr2d[names != 'Joe']

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [12]:
# fancy indexing
print(arr2d[[2, 1, 0, 1]])
row = np.arange(arr2d.shape[0])
col = np.array([1, 2, 0])
print(arr2d[row, col])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[1 6 8]


In [22]:
# ufuncs
arr = np.arange(1, 11)
(arr - np.mean(arr)) / np.std(arr)

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [21]:
# aggregation
arr2d = np.arange(1, 7).reshape((2, 3))
np.sum(arr2d, axis = 1)

array([ 6, 15])

In [19]:
# high dimensional
arr3d = np.arange(24).reshape((2, 3, 4))
np.sum(arr3d, axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])